name: Build docker image

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: windows-latest

        steps:
        - name: check out code
          uses: actions/checkout@v2

        - name: login
          uses: docker/login-action@v2
          with:
            username:
            password:

        - name: build image
          run: |
            docker build -t demo .

        - name: push image
          run: |
            docker push demo:latest
